### ISSUE TITLE
To do list의 할일 필터 기능 관련 api 

### ISSUE THREAD

**Issue by 253eosam** [DDD05/To-do-list-noti2007#14]
`http://localhost:8080/posts/condition/` 을 원하는 조건을 넣어 요청시 400 에러

- isCompleted 미 입력시 에러 -> 미입력 가능, 상관없이 모든 조건 검색
- keyword 값을 비우게됐을때 필수값 필요 -> 비웠을때 전체 조회 기능 추가

![image](https://user-images.githubusercontent.com/41896147/103748651-c7ce0580-5047-11eb-8651-5fbf2a0d7cc8.png)

**Comment by 253eosam** [comment]
- 할일 등록 글자 갯수 제한 몇글자인가요 ?? 정책이 어떻게되는지 ...
- 사용자 변경 api 사용 가이드 부탁드립니다.

**Comment by leehojun078** [comment]
inCompleted 값은 true, false 인데 미완료된 게시글만 볼 것이냐? 에 대한 값을 적어 주면 됩니다.

- 완료, 미완료 게시글 보기 : ( inCompleted : false)
- 미완료 게시글 보기 : (inCompleted : true)
